AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Alexa Skill - Key Value Store (amzn1.ask.skill.ea3af308-64af-4316-9a1a-67e69a7f50b9)
Resources:
  alexa-skill-kv-store:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./build.zip
      MemorySize: 128
      Timeout: 3
